/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    people: PersonAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    people: Person;
    personLabels: PersonLabel;
    geoNodes: GeoNode;
    geoVillages: GeoVillage;
    geoPincodes: GeoPincode;
    orgAssignments: OrgAssignment;
    projects: Project;
    projectStages: ProjectStage;
    events: Event;
    lists: List;
    listMembers: ListMember;
    attendance: Attendance;
    socialPosts: SocialPost;
    skills: Skill;
    skillClaims: SkillClaim;
    media: Media;
    otpRequests: OtpRequest;
    news: News;
    activities: Activity;
    galleryAlbums: GalleryAlbum;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    personLabels: PersonLabelsSelect<false> | PersonLabelsSelect<true>;
    geoNodes: GeoNodesSelect<false> | GeoNodesSelect<true>;
    geoVillages: GeoVillagesSelect<false> | GeoVillagesSelect<true>;
    geoPincodes: GeoPincodesSelect<false> | GeoPincodesSelect<true>;
    orgAssignments: OrgAssignmentsSelect<false> | OrgAssignmentsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    projectStages: ProjectStagesSelect<false> | ProjectStagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    lists: ListsSelect<false> | ListsSelect<true>;
    listMembers: ListMembersSelect<false> | ListMembersSelect<true>;
    attendance: AttendanceSelect<false> | AttendanceSelect<true>;
    socialPosts: SocialPostsSelect<false> | SocialPostsSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    skillClaims: SkillClaimsSelect<false> | SkillClaimsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    otpRequests: OtpRequestsSelect<false> | OtpRequestsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    galleryAlbums: GalleryAlbumsSelect<false> | GalleryAlbumsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin | Person;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PersonAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  phone: string;
  name?: string | null;
  /**
   * Set only when one phone was shared by different names in the import: all distinct names, joined with ' | '. In that case name is set to 'multiple'.
   */
  altNames?: string | null;
  dob?: string | null;
  gender?: ('male' | 'female') | null;
  pincode?: string | null;
  referredBy?: (number | null) | Person;
  /**
   * Which program/project they joined
   */
  programId?: (number | null) | Project;
  geoNode?: (number | null) | GeoNode;
  otpVerified?: boolean | null;
  /**
   * Base-36 of phone, 7-char uppercase
   */
  referralCode?: string | null;
  source?: ('signup' | 'excel-import' | 'org-added' | 'event') | null;
  /**
   * Original import strings, for re-mapping after geo merges
   */
  rawGeoText?: {
    mandalam?: string | null;
    district?: string | null;
    union?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  collection: 'people';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  slug?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startDate?: string | null;
  endDate?: string | null;
  status?: ('planned' | 'active' | 'completed' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geoNodes".
 */
export interface GeoNode {
  id: number;
  name: string;
  nameTamil?: string | null;
  level: 'state' | 'region' | 'mandalam' | 'district' | 'union' | 'panchayat' | 'temple';
  /**
   * Parent node (null for State). Region↔Mandalam set manually.
   */
  parent?: (number | null) | GeoNode;
  /**
   * e.g. Mandalam number
   */
  code?: string | null;
  /**
   * Spelling variants seen in imports
   */
  aliases?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * If set, this node was merged into the target (dedup).
   */
  mergedInto?: (number | null) | GeoNode;
  pincodes?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personLabels".
 */
export interface PersonLabel {
  id: number;
  person: number | Person;
  key: string;
  value?: string | null;
  setBy?: (number | null) | Person;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geoVillages".
 */
export interface GeoVillage {
  id: number;
  /**
   * LGD village code
   */
  villageCode: string;
  village: string;
  villageTamil?: string | null;
  gramPanchayat?: string | null;
  /**
   * Panchayat union block
   */
  block?: string | null;
  taluk?: string | null;
  district?: string | null;
  districtCode?: string | null;
  talukCode?: string | null;
  blockCode?: string | null;
  pincode?: string | null;
  /**
   * Confidence of the derived pincode
   */
  pincodeMatchLevel?: ('high' | 'good' | 'medium' | 'low') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geoPincodes".
 */
export interface GeoPincode {
  id: number;
  pincode: string;
  office: string;
  /**
   * H.O / S.O / B.O
   */
  officeType?: string | null;
  delivery?: string | null;
  taluk?: string | null;
  district?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orgAssignments".
 */
export interface OrgAssignment {
  id: number;
  person: number | Person;
  geoNode: number | GeoNode;
  role:
    | 'state_admin'
    | 'regional_organiser'
    | 'zonal_organiser'
    | 'district_organiser'
    | 'union_coordinator'
    | 'panchayat_coordinator'
    | 'temple_coordinator';
  active?: boolean | null;
  assignedBy?: (number | null) | Person;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectStages".
 */
export interface ProjectStage {
  id: number;
  project: number | Project;
  name: string;
  order: number;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  name: string;
  kind: 'local' | 'campaign_parent' | 'campaign_session';
  project?: (number | null) | Project;
  stage?: (number | null) | ProjectStage;
  /**
   * For local/district sessions: the district. For a campaign: the scope (state/region/mandalam/district) to fan out across.
   */
  geoNode?: (number | null) | GeoNode;
  /**
   * The campaign this district session belongs to.
   */
  parentEvent?: (number | null) | Event;
  date?: string | null;
  createdBy?: (number | null) | Person;
  /**
   * District reps running this event
   */
  organisers?: (number | Person)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lists".
 */
export interface List {
  id: number;
  name: string;
  project?: (number | null) | Project;
  acquisitionChannel?: ('social_media' | 'otp_verification' | 'event' | 'import' | 'other') | null;
  geoScope?: (number | null) | GeoNode;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listMembers".
 */
export interface ListMember {
  id: number;
  list: number | List;
  person: number | Person;
  enteredAtStage?: (number | null) | ProjectStage;
  status?: ('active' | 'dropped' | 'converted') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance".
 */
export interface Attendance {
  id: number;
  event: number | Event;
  person: number | Person;
  present?: boolean | null;
  recordedBy?: (number | null) | Person;
  recordedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socialPosts".
 */
export interface SocialPost {
  id: number;
  author?: (number | null) | Person;
  /**
   * Must be within the author's downward scope (enforced in module).
   */
  geoNode?: (number | null) | GeoNode;
  images?: (number | Media)[] | null;
  caption?: string | null;
  status?: ('published' | 'hidden') | null;
  /**
   * Marked by upper levels for the social-media team.
   */
  curatedForSocial?: boolean | null;
  curatedBy?: (number | null) | Person;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feed?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  title: string;
  person: number | Person;
  tags?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  /**
   * Free-time / availability
   */
  availability?: string | null;
  status?: ('open' | 'claimed' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skillClaims".
 */
export interface SkillClaim {
  id: number;
  skill: number | Skill;
  claimedBy: number | Person;
  note?: string | null;
  status?: ('requested' | 'accepted' | 'declined' | 'done') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otpRequests".
 */
export interface OtpRequest {
  id: number;
  phone: string;
  codeHash: string;
  expiresAt: string;
  attempts?: number | null;
  consumed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  slug: string;
  date?: string | null;
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Path under /public or an uploaded media URL
   */
  image?: string | null;
  coverImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  title: string;
  href?: string | null;
  image?: string | null;
  blurb?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleryAlbums".
 */
export interface GalleryAlbum {
  id: number;
  /**
   * Album group heading
   */
  groupTitle?: string | null;
  title: string;
  slug: string;
  /**
   * First image is the cover
   */
  images?:
    | {
        path?: string | null;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'personLabels';
        value: number | PersonLabel;
      } | null)
    | ({
        relationTo: 'geoNodes';
        value: number | GeoNode;
      } | null)
    | ({
        relationTo: 'geoVillages';
        value: number | GeoVillage;
      } | null)
    | ({
        relationTo: 'geoPincodes';
        value: number | GeoPincode;
      } | null)
    | ({
        relationTo: 'orgAssignments';
        value: number | OrgAssignment;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'projectStages';
        value: number | ProjectStage;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'lists';
        value: number | List;
      } | null)
    | ({
        relationTo: 'listMembers';
        value: number | ListMember;
      } | null)
    | ({
        relationTo: 'attendance';
        value: number | Attendance;
      } | null)
    | ({
        relationTo: 'socialPosts';
        value: number | SocialPost;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'skillClaims';
        value: number | SkillClaim;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'otpRequests';
        value: number | OtpRequest;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'galleryAlbums';
        value: number | GalleryAlbum;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'people';
        value: number | Person;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'people';
        value: number | Person;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  phone?: T;
  name?: T;
  altNames?: T;
  dob?: T;
  gender?: T;
  pincode?: T;
  referredBy?: T;
  programId?: T;
  geoNode?: T;
  otpVerified?: T;
  referralCode?: T;
  source?: T;
  rawGeoText?:
    | T
    | {
        mandalam?: T;
        district?: T;
        union?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personLabels_select".
 */
export interface PersonLabelsSelect<T extends boolean = true> {
  person?: T;
  key?: T;
  value?: T;
  setBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geoNodes_select".
 */
export interface GeoNodesSelect<T extends boolean = true> {
  name?: T;
  nameTamil?: T;
  level?: T;
  parent?: T;
  code?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  mergedInto?: T;
  pincodes?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geoVillages_select".
 */
export interface GeoVillagesSelect<T extends boolean = true> {
  villageCode?: T;
  village?: T;
  villageTamil?: T;
  gramPanchayat?: T;
  block?: T;
  taluk?: T;
  district?: T;
  districtCode?: T;
  talukCode?: T;
  blockCode?: T;
  pincode?: T;
  pincodeMatchLevel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geoPincodes_select".
 */
export interface GeoPincodesSelect<T extends boolean = true> {
  pincode?: T;
  office?: T;
  officeType?: T;
  delivery?: T;
  taluk?: T;
  district?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orgAssignments_select".
 */
export interface OrgAssignmentsSelect<T extends boolean = true> {
  person?: T;
  geoNode?: T;
  role?: T;
  active?: T;
  assignedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectStages_select".
 */
export interface ProjectStagesSelect<T extends boolean = true> {
  project?: T;
  name?: T;
  order?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  project?: T;
  stage?: T;
  geoNode?: T;
  parentEvent?: T;
  date?: T;
  createdBy?: T;
  organisers?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lists_select".
 */
export interface ListsSelect<T extends boolean = true> {
  name?: T;
  project?: T;
  acquisitionChannel?: T;
  geoScope?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listMembers_select".
 */
export interface ListMembersSelect<T extends boolean = true> {
  list?: T;
  person?: T;
  enteredAtStage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance_select".
 */
export interface AttendanceSelect<T extends boolean = true> {
  event?: T;
  person?: T;
  present?: T;
  recordedBy?: T;
  recordedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socialPosts_select".
 */
export interface SocialPostsSelect<T extends boolean = true> {
  author?: T;
  geoNode?: T;
  images?: T;
  caption?: T;
  status?: T;
  curatedForSocial?: T;
  curatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  title?: T;
  person?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  description?: T;
  availability?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skillClaims_select".
 */
export interface SkillClaimsSelect<T extends boolean = true> {
  skill?: T;
  claimedBy?: T;
  note?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feed?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otpRequests_select".
 */
export interface OtpRequestsSelect<T extends boolean = true> {
  phone?: T;
  codeHash?: T;
  expiresAt?: T;
  attempts?: T;
  consumed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  excerpt?: T;
  body?: T;
  image?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  title?: T;
  href?: T;
  image?: T;
  blurb?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleryAlbums_select".
 */
export interface GalleryAlbumsSelect<T extends boolean = true> {
  groupTitle?: T;
  title?: T;
  slug?: T;
  images?:
    | T
    | {
        path?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  name?: string | null;
  shortName?: string | null;
  tagline?: string | null;
  donateUrl?: string | null;
  contact?: {
    address?: string | null;
    phone?: string | null;
    phoneHref?: string | null;
    email?: string | null;
  };
  stats?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  tagline?: T;
  donateUrl?: T;
  contact?:
    | T
    | {
        address?: T;
        phone?: T;
        phoneHref?: T;
        email?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}